#!/usr/bin/env python3
"""Generates imgf_bench_assets.h: a PNG and (when cjpeg is on PATH) a
progressive JPEG of the same procedural picture.

The baseline JPEG the bench uses is encoded on the target at run time by
imgf_jpege, so it needs no asset. Progressive JPEG has no encoder in
image_framework, hence the build-time dependency on libjpeg's cjpeg; without it
the progressive case is skipped.

Usage: gen_assets.py <out.h> [width] [height] [grain]
"""
import math
import os
import shutil
import struct
import subprocess
import sys
import tempfile
import zlib


def picture(w, h, grain):
    """Photo-like rows: low-frequency colour field, mid-frequency structure,
    fine grain. The grain is what keeps the entropy stages honest."""
    rows = []
    s = 2463534242
    for y in range(h):
        row = bytearray()
        fy = y / h
        for x in range(w):
            fx = x / w
            p = (math.sin(fx * 9.0) + math.sin(fy * 7.0 + 1.3) +
                 0.5 * math.sin((fx + fy) * 15.0) +
                 0.4 * math.sin(math.hypot(fx - 0.4, fy - 0.6) * 22.0))
            s ^= (s << 13) & 0xFFFFFFFF
            s ^= s >> 17
            s ^= (s << 5) & 0xFFFFFFFF
            n = (((s >> 8) & 0x3F) - 32) * grain
            d = 5.0 * (math.sin(x * 2.1) * math.sin(y * 1.7) +
                        0.6 * math.sin((x + y) * 1.13) +
                        0.5 * math.sin((x - y) * 0.71)) * (0.35 + 0.65 * fy)
            for v in (128 + 36 * p + 60 * fx + n + d,
                      128 + 80 * math.sin(p * 1.7) + 50 * fy + n + d,
                      128 + 70 * math.cos(p * 1.1 + fx * 3.0) + n - d):
                row.append(0 if v < 0 else (255 if v > 255 else int(v)))
        rows.append(bytes(row))
    return rows


def png(w, h, rows):
    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data +
                struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    raw = bytearray()
    for r in rows:
        raw.append(1)  # Sub
        raw += bytes((r[i] - (r[i - 3] if i >= 3 else 0)) & 0xFF for i in range(len(r)))
    return (b"\x89PNG\r\n\x1a\n" +
            chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)) +
            chunk(b"IDAT", zlib.compress(bytes(raw), 6)) +
            chunk(b"IEND", b""))


def progressive_jpeg(w, h, rows, quality=85):
    cjpeg = shutil.which("cjpeg")
    if not cjpeg:
        return None
    with tempfile.TemporaryDirectory() as td:
        ppm = os.path.join(td, "src.ppm")
        with open(ppm, "wb") as f:
            f.write(b"P6\n%d %d\n255\n" % (w, h))
            for r in rows:
                f.write(r)
        out = subprocess.run([cjpeg, "-quality", str(quality), "-progressive",
                              "-sample", "2x2", ppm],
                             capture_output=True, check=True)
        return out.stdout


def emit(f, name, data):
    f.write("static const unsigned char %s[] = {\n" % name)
    for i in range(0, len(data), 16):
        f.write("    " + "".join("%d," % b for b in data[i:i + 16]) + "\n")
    f.write("};\n\n")


def main():
    out_path = sys.argv[1]
    w = int(sys.argv[2]) if len(sys.argv) > 2 else 960
    h = int(sys.argv[3]) if len(sys.argv) > 3 else 540
    grain = float(sys.argv[4]) if len(sys.argv) > 4 else 0.15

    rows = picture(w, h, grain)
    png_bytes = png(w, h, rows)
    jpg_bytes = progressive_jpeg(w, h, rows)

    tmp = out_path + ".tmp"
    with open(tmp, "w") as f:
        f.write("/* Generated by gen_assets.py — do not edit. */\n#pragma once\n\n")
        f.write("#define IMGF_BENCH_ASSET_W %d\n#define IMGF_BENCH_ASSET_H %d\n\n" % (w, h))
        emit(f, "kBenchPng", png_bytes)
        if jpg_bytes:
            f.write("#define IMGF_BENCH_HAS_PROGRESSIVE 1\n")
            emit(f, "kBenchProgJpeg", jpg_bytes)
        else:
            f.write("#define IMGF_BENCH_HAS_PROGRESSIVE 0\n")
            f.write("static const unsigned char kBenchProgJpeg[1];\n\n")
    os.replace(tmp, out_path)
    sys.stderr.write("gen_assets: %dx%d  png %d B  progressive jpeg %s\n" %
                     (w, h, len(png_bytes), len(jpg_bytes) if jpg_bytes else "skipped (no cjpeg)"))


main()
