/*
 * Generates jpeg_fixtures.h: small baseline JPEGs (built with libjpeg) used by
 * the host tests to exercise the in-tree JPEG decoder. JPEG is lossy, so the
 * tests assert dimensions + approximate pixel values, not exact bytes.
 * Regenerate: cc gen_jpeg.c $(pkg-config --cflags --libs libjpeg) -o gen && ./gen > jpeg_fixtures.h
 */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <jpeglib.h>

static void emit(const char *name, const unsigned char *data, unsigned long len) {
    printf("static const unsigned char %s[] = {\n", name);
    for (unsigned long i = 0; i < len; i++)
        printf("%d,%s", data[i], (i % 16 == 15) ? "\n" : "");
    printf("\n};\n\n");
}

static void make(const char *name, int w, int h, int nc, J_COLOR_SPACE cs,
                 int subsample, const unsigned char *pixels, int quality) {
    struct jpeg_compress_struct cinfo;
    struct jpeg_error_mgr jerr;
    cinfo.err = jpeg_std_error(&jerr);
    jpeg_create_compress(&cinfo);
    unsigned char *buf = NULL;
    unsigned long len = 0;
    jpeg_mem_dest(&cinfo, &buf, &len);
    cinfo.image_width = w;
    cinfo.image_height = h;
    cinfo.input_components = nc;
    cinfo.in_color_space = cs;
    jpeg_set_defaults(&cinfo);
    jpeg_set_quality(&cinfo, quality, TRUE);
    if (cs == JCS_RGB && subsample) {  // force 4:2:0 to exercise chroma upsample
        cinfo.comp_info[0].h_samp_factor = 2;
        cinfo.comp_info[0].v_samp_factor = 2;
        cinfo.comp_info[1].h_samp_factor = 1;
        cinfo.comp_info[1].v_samp_factor = 1;
        cinfo.comp_info[2].h_samp_factor = 1;
        cinfo.comp_info[2].v_samp_factor = 1;
    }
    jpeg_start_compress(&cinfo, TRUE);
    while (cinfo.next_scanline < cinfo.image_height) {
        JSAMPROW row = (JSAMPROW)(pixels + (size_t)cinfo.next_scanline * w * nc);
        jpeg_write_scanlines(&cinfo, &row, 1);
    }
    jpeg_finish_compress(&cinfo);
    emit(name, buf, len);
    free(buf);
    jpeg_destroy_compress(&cinfo);
}

int main(void) {
    printf("/* Generated by gen_jpeg.c — do not edit. */\n#pragma once\n\n");

    // 16x16 flat gray = 128.
    unsigned char gray[16 * 16];
    for (int i = 0; i < 16 * 16; i++) gray[i] = 128;
    make("kJpgGrayFlat", 16, 16, 1, JCS_GRAYSCALE, 0, gray, 95);

    // 16x16 grayscale, dark left half / bright right half.
    unsigned char split[16 * 16];
    for (int y = 0; y < 16; y++)
        for (int x = 0; x < 16; x++) split[y * 16 + x] = x < 8 ? 40 : 220;
    make("kJpgGraySplit", 16, 16, 1, JCS_GRAYSCALE, 0, split, 95);

    // 16x16 solid red (220,30,30), 4:2:0.
    unsigned char red[16 * 16 * 3];
    for (int i = 0; i < 16 * 16; i++) { red[3*i]=220; red[3*i+1]=30; red[3*i+2]=30; }
    make("kJpgRgbRed", 16, 16, 3, JCS_RGB, 1, red, 95);

    // 64x64 flat gray = 100, for the decode-time downscale test.
    unsigned char big[64 * 64];
    for (int i = 0; i < 64 * 64; i++) big[i] = 100;
    make("kJpgGrayBig", 64, 64, 1, JCS_GRAYSCALE, 0, big, 95);

    return 0;
}
